### ISSUE TITLE
About conditional utilization rate

### ISSUE THREAD

**Issue by jasperhyp** [nyukat/greedy_multimodal_learning#1]
Hi,  Thanks for sharing the code of your great work!  I was just curious why the claim " $d_{util}(f)$ is bounded between -1 and 1" holds.  I'm not sure but there seems no theoretical guarantee that $A(f_0')$ is always smaller than $A(f_0)$, for example.  Thanks for your attention!

**Comment by jasperhyp** [comment]
Also, what is the `random` version?  I didn't notice the paper introduce this... maybe i'm missing something

**Comment by SebastianHafner** [comment]
First, I would also like to congratulate the authors on their very interesting paper.

From my understanding, the random version randomly chooses for each step between taking a regular step (i.e., updating everything) and a re-balancing step for either modality (i.e., updating only one of the uni-modal branches).

Regarding your first comment, I tested the concept of conditional utilization rates on my own dataset and encountered cases where I got negative values. Therefore, I think you are right in your statement that the difference between the conditional learning rates can be outside the range [-1, 1].

I am happy to be corrected on either point, though.

**Comment by wooginawunan** [comment]
We are glad that you find our work interesting! 

Regarding the random version, @SebastianHafner's interpretation is correct. Please also see our definition of it below:

After performing regular steps in the first epoch, we let the model take a step that is randomly sampled from, regular step, re-balancing step on $m_0$, and re-balancing step on $m_1$.

For the other point, we agree that it can happen that $A(f'_0)>A(f'_1)$. We are sorry that we didn't provide clear assumptions when we discuss the range of the $d_u$. We didn't aim to provide a theoretical discussion here but hope to give readers a sense of how significant the model is biased to using a single modality given the number observed.
